#!/bin/bash

### TODO: query FW via RedFish mechanisms (or amd-smi/rocm-smi)
#verbose Checking Firmware
#compare2 "$(/usr/sbin/dmidecode -s bios-version)" "1.8.0" "1.9.0" "BIOS version does not match expected version"
#compare "$(/usr/sbin/dmidecode |awk '/BIOS Revision:/ {print $3}')" "5.21" "BIOS Revison does not match expected version"

exit 0
